sudo: required
services:
  - docker
before_install:
  - docker build -t nm926/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nm926/react-test npm test  -- --coverage

after_success:
  - docker build -t neelsky/multi-client  ./client
  - docker build -t neelsky/multi-nginx   ./nginx
  - docker build -t neelsky/multi-server  ./server
  - docker build -t neelsky/multi-worker  ./worker

# Log in to the docker cli

  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

# Take those images and push them to docker hub

  - docker push neelsky/multi-client
  - docker push neelsky/multi-nginx
  - docker push neelsky/multi-server
  - docker push neelsky/multi-worker
